### ISSUE TITLE
Hozzáférési hiba - sajátosság Vivinél

### ISSUE THREAD

**Issue by pvivien** [zsiki/pdata#1]
ProgrammingError: permission denied for relation pdata.
A hiba a törlés művelet folyamán aktiválódik.

**Comment by zsiki** [comment]
Hi Vivien,
I suppose it is a local problem. did you GRANT insert, update, delete on the pdata table to the web server user (or public)? Try:
GRANT select, insert, update, delete ON TABLE pdata TO public;

**Comment by pvivien** [comment]
Thank you for your advice, it solved my problem.
